- name: Install Python pip
  become: true
  apt:
    name: python3-pip
    state: present

- name: Install python3-venv
  become: true
  apt:
    name: python3-venv
    state: present

- name: install python-setuptools
  become: true
  package:
    name: python-setuptools
    state: present

- name: Install pymongo package
  become: true
  pip:
    name: pymongo
    state: present


- name: INSTALL pyOpenSSL for MongoDB
  become: true
  ansible.builtin.pip:
    name: pyOpenSSL


- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  when: mongo_bin.stat.exists == False

       
- name: INSTALL the repo key
  become: true
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
  when: mongo_bin.stat.exists == False

- name: INSTALL mongo deb repository
  tags: mongoinstall
  become: true
  ansible.builtin.apt_repository:
    #apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse"
    update_cache: yes
    state: present
  when: mongo_bin.stat.exists == False

- name: INSTALL mongodb
  become: true
  apt: pkg=mongodb-org state=latest update_cache=yes
  #notify:
  #- start mongodb
  when: mongo_bin.stat.exists == False

- name: COPY mongo config file
  become: true
  tags: mongoconfig
  copy:
    src: mongo-config
    dest: /etc/mongod.conf
    #owner: root
    #group: root
    #mode: 0644

- name: COPY mongo key file
  tags: mongokey
  become: true
  copy:
    src: replica-key-file
    dest: /etc/mongokeyfile
    owner: mongodb
    group: mongodb
    mode: 0400

- name: ADD a line in var.conf
  become: true
  ansible.builtin.lineinfile:
    path: /usr/lib/tmpfiles.d/var.conf
    state: present
    line: d /var/run/mongodb 0750 mongodb mongodb -
    create: true

- name: CREATE storage directory
  tags: createpid
  become: true
  ansible.builtin.file:
    path: /storage/db
    state: directory
    owner: mongodb
    group: mongodb

- name: CREATE PID directory
  tags: createpid
  become: true
  ansible.builtin.file:
    path: /var/run/mongodb/
    state: directory
    owner: mongodb
    group: mongodb
   #mode: '0644'
    
- name: CREATE PID file
  tags: createpid
  become: true
  ansible.builtin.file:
   path: /var/run/mongodb/mongod.pid
   state: touch
   owner: mongodb
   group: mongodb
   #mode: '0644'
   
- name: START mongodb
  #notify:
  tags: mongostart
  become: true
  ansible.builtin.service:
    name: mongod
    state: started

# - name: Ensure replicaset rs0 exists
#   become: true
#   community.mongodb.mongodb_replicaset:
#     login_host: localhost
#     login_user: admin
#     login_password: admin
#     replica_set: rs0

- name: Initialise MongoDB Replicaset rs0
  community.mongodb.mongodb_replicaset:
    login_database: "admin"
    login_host: localhost
    replica_set: "rs0"
  #   members:
  #     - "mongodb1"
  #     - "mongodb2"
  #     - "mongodb3"
  # when: ansible_hostname == "mongodb1"
  register: repl